version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:15
    container_name: nestjs-prisma-sample
    volumes:
      - db-data:/var/lib/postgresql/nestjs-prisma-sample/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  tracing:
    image: 'jaegertracing/all-in-one:latest'
    ports:
      # see: https://www.jaegertracing.io/docs/1.43/getting-started/#all-in-one
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
    environment:
      - COLLECTOR_OTLP_ENABLED=true
