version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: nestjs-prisma-github-actions
    volumes:
      - db-data:/var/lib/postgresql/nestjs-prisma-github-actions/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

